In [27]:
import pandas as pd

data = pd.read_csv("channel dataset/data.csv")
print( data.columns )
print( data.head() )

Index(['Index', 'Channel', 'Time', 'Show', 'Genre'], dtype='object')
   Index       Channel   Time                                Show  \
0      0  Star Plus HD  00:00                Devon Ke Dev Mahadev   
1      1  Star Plus HD  00:45  Savdhaan India : India Fights Back   
2      2  Star Plus HD  01:30  Savdhaan India : India Fights Back   
3      3  Star Plus HD  02:15  Savdhaan India : India Fights Back   
4      4  Star Plus HD  03:00  Savdhaan India : India Fights Back   

                                   Genre  
0  Indian,Hindi,television series,darama  
1                     indian,hindi,crime  
2                     indian,hindi,crime  
3                     indian,hindi,crime  
4                     indian,hindi,crime  


In [28]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [29]:
featurematrix = cv.fit_transform(data["Genre"].to_numpy())
print( cv.get_feature_names())
print( featurematrix.toarray())

['8888', 'action', 'adventure', 'advertisement', 'africa', 'african', 'agenda', 'agendas', 'airplane', 'airport', 'aliens', 'american', 'animated', 'animation', 'antique', 'antiques', 'art', 'artist', 'artists', 'asian', 'athlete', 'australian', 'backtoback', 'bakery', 'bidding', 'blogging', 'bollywood', 'british', 'business', 'buy', 'cake', 'car', 'cartoon', 'cat', 'celebrity', 'chat', 'chef', 'chemistry', 'chinese', 'city', 'cockroach', 'comedy', 'comic', 'competition', 'competitive', 'contest', 'cook', 'cooking', 'craft', 'crash', 'cricket', 'crime', 'crome', 'csx', 'culinery', 'culture', 'curious', 'current', 'daily', 'dance', 'darama', 'dating', 'debate', 'designer', 'designs', 'destruction', 'devotion', 'disaster', 'discovery', 'discussions', 'documentarty', 'documentary', 'documnetray', 'drama', 'drugs', 'economy', 'electric', 'elon', 'english', 'englishcartoon', 'entertainment', 'exercise', 'experiments', 'explore', 'family', 'famous', 'fantasy', 'fashion', 'fiction', 'films', 

In [30]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity( featurematrix)
print( similarity_matrix)

[[1.         0.51639778 0.51639778 ... 0.2        0.2        0.18257419]
 [0.51639778 1.         1.         ... 0.25819889 0.25819889 0.23570226]
 [0.51639778 1.         1.         ... 0.25819889 0.25819889 0.23570226]
 ...
 [0.2        0.25819889 0.25819889 ... 1.         0.2        0.18257419]
 [0.2        0.25819889 0.25819889 ... 0.2        1.         0.18257419]
 [0.18257419 0.23570226 0.23570226 ... 0.18257419 0.18257419 1.        ]]


In [31]:
index_of_show_user_watched = data[ data.Show == "Avatar"]["Index"].values[0]

print( index_of_show_user_watched)


96


In [32]:
contentsimilararray = similarity_matrix[index_of_show_user_watched ] 

list_of_pair = list( enumerate(contentsimilararray ) )

print( list_of_pair)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.5477225575051662), (30, 0.36514837167011077), (31, 0.1666666666666667), (32, 0.3872983346207417), (33, 0.2357022603955159), (34, 0.36514837167011077), (35, 0.36514837167011077), (36, 0.36514837167011077), (37, 0.0), (38, 0.0), (39, 0.0), (40, 0.0), (41, 0.18257418583505539), (42, 0.0), (43, 0.0), (44, 0.0), (45, 0.0), (46, 0.0), (47, 0.0), (48, 0.5477225575051662), (49, 0.7715167498104596), (50, 0.6666666666666669), (51, 0.8333333333333336), (52, 0.6666666666666669), (53, 0.8333333333333336), (54, 0.6666666666666669), (55, 0.6666666666666669), (56, 0.36514837167011077), (57, 0.5000000000000001), (58, 0.0), (59, 0.0), (60, 0.0), (61, 0.0), (62, 0.0), (63, 0.0), (64, 0.0), (65

In [33]:
def mysortfunc(item):
    return item[1]

list_of_pair.sort( reverse =True ,key = mysortfunc )
print( list_of_pair )

[(96, 1.0000000000000002), (51, 0.8333333333333336), (53, 0.8333333333333336), (49, 0.7715167498104596), (90, 0.7302967433402215), (93, 0.7302967433402215), (98, 0.7302967433402215), (50, 0.6666666666666669), (52, 0.6666666666666669), (54, 0.6666666666666669), (55, 0.6666666666666669), (89, 0.6666666666666669), (29, 0.5477225575051662), (48, 0.5477225575051662), (94, 0.5477225575051662), (95, 0.5477225575051662), (97, 0.5477225575051662), (57, 0.5000000000000001), (91, 0.5000000000000001), (92, 0.5000000000000001), (76, 0.4082482904638631), (83, 0.4082482904638631), (32, 0.3872983346207417), (30, 0.36514837167011077), (34, 0.36514837167011077), (35, 0.36514837167011077), (36, 0.36514837167011077), (56, 0.36514837167011077), (270, 0.3333333333333334), (295, 0.3333333333333334), (262, 0.3086066999241838), (263, 0.3086066999241838), (273, 0.3086066999241838), (33, 0.2357022603955159), (77, 0.2357022603955159), (78, 0.2357022603955159), (79, 0.2357022603955159), (80, 0.2357022603955159), (

In [34]:
for show_tuple in list_of_pair[0:5]:
    currow = data[ data.index == show_tuple[0] ] 
    print( currow["Show"].values[0] , " ", currow["Channel"].values[0]," ", currow["Time"].values[0])


Avatar   Star Movies HD   04:38
Aeon Flux   WB   03:00
After The Sunset   WB   07:30
Deep Impact   WB   11:00
The Book Of Life   Star Movies HD   05:22


In [35]:
import numpy as np
contents = data["Genre"].to_numpy()



string =  data[ data.Show == "Avatar" ]["Genre"].values[0] 
string+= ','+ data[ data.Show == "IPL Highlight" ]["Genre"].values[0] 
print(string)
contents = np.append( contents, string )



for i in range(0,len(contents) ):
       contents[i] = contents[i].replace(" ","")
#print(contents)

English,movie,American,Science,fiction,action,English, Cricket, Tournaments, Highlights


In [36]:
cv2 = CountVectorizer()
fm2 = cv.fit_transform( contents )
print( cv.get_feature_names( ))
sm2 = cosine_similarity(fm2)
sm2

['action', 'adventure', 'advertisement', 'africa', 'african', 'agenda', 'agendas', 'airplane', 'airport', 'aliens', 'american', 'animated', 'animationseries', 'antique', 'antiques', 'art', 'artist', 'artists', 'asiangames', 'australian', 'backtobackmusic', 'bakery', 'bidding', 'blogging', 'bollywood', 'british', 'business', 'buy', 'cake', 'car', 'carrace', 'cartoon', 'cat', 'celebrity', 'chat', 'chef', 'chemistry', 'chinese', 'city', 'cockroach', 'comedy', 'comic', 'competition', 'competitive', 'contest', 'cook', 'cooking', 'craft', 'crash', 'cricket', 'crime', 'crome', 'culinery', 'culture', 'curious', 'currentupdates', 'daily', 'dance', 'darama', 'dating', 'debate', 'designer', 'designs', 'destruction', 'devotion', 'disaster', 'discovery', 'discussions', 'documentarty', 'documentary', 'documnetray', 'drama', 'drugs', 'economy', 'electriccarrace', 'elonmusk', 'english', 'englishcartoon', 'entertainment', 'exercise', 'experiments', 'explore', 'family', 'famous', 'fantasy', 'fashion', '

array([[1.        , 0.57735027, 0.57735027, ..., 0.2236068 , 0.20412415,
        0.        ],
       [0.57735027, 1.        , 1.        , ..., 0.25819889, 0.23570226,
        0.        ],
       [0.57735027, 1.        , 1.        , ..., 0.25819889, 0.23570226,
        0.        ],
       ...,
       [0.2236068 , 0.25819889, 0.25819889, ..., 1.        , 0.18257419,
        0.        ],
       [0.20412415, 0.23570226, 0.23570226, ..., 0.18257419, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [37]:
contents_similarwithuser = sm2[299]
contents_similarwithuser

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.38729833,
       0.25819889, 0.12909944, 0.32732684, 0.16666667, 0.28867513,
       0.25819889, 0.25819889, 0.        , 0.        , 0.        ,
       0.        , 0.12909944, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.51639778, 0.65465367,
       0.58925565, 0.70710678, 0.58925565, 0.70710678, 0.58925565,
       0.58925565, 0.38729833, 0.47140452, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.12909944,
       0.14433757, 0.14433757, 0.14433757, 0.14433757, 0.14433

In [38]:

list_of_similar = list( enumerate(contents_similarwithuser ) )

list_of_similar.sort(reverse=True, key  =mysortfunc)

print('Shows Recommended On basis of user history')

for pair in list_of_similar[1:6]:
    print( data[ data.Index == pair[0] ]["Show"].values[0] )

Avatar
IPL Highlight
ICC Cricket World Cup Higlights
IPL Highlight
Aeon Flux
